version: 2
jobs:
  build:
    working_directory: ~/mssc-beer-service
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout

      - restore_cache:
          key: mssc-beer-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: mssc-beer-service-{{ checksum "pom.xml" }}
      - run: mvn compile
